version: "3.9"
services:
  db:
    image: postgres:14.4-alpine3.16
    env_file: ".env"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      target: development
    command: "rails s"
    stdin_open: true
    tty: true
    env_file: ".env"
    volumes:
      - "./:/app"
      - gem_cache:/usr/local/bundle
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  gem_cache:
  pg_data:
